repos:
  - repo: local
    hooks:
      - id: ruff
        language: python
        name: ruff
        pass_filenames: false
        language_version: python3.8
        entry: poetry run ruff --fix --exit-non-zero-on-fix --show-fixes fastapi_query examples tests
